# Generated by Django 5.0.6 on 2024-06-27 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_options_post_artist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='image_url',
        ),
        migrations.AddField(
            model_name='post',
            name='source_url',
            field=models.URLField(max_length=300, null=True),
        ),
    ]
