# Generated by Django 5.0.6 on 2024-06-28 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_tag_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='icons/'),
        ),
    ]
